import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js';

const PRODUCT=[{id:'maito',name:'Maito',price:1.49,color:0xf4f3ef,kind:'carton'},{id:'leipa',name:'Leipä',price:2.29,color:0xad7434,kind:'bread'},{id:'mehu',name:'Mehu',price:1.90,color:0xffa53b,kind:'carton'},{id:'vesi',name:'Vesi',price:1,color:0x79cbe5,kind:'bottle'},{id:'kahvi',name:'Kahvi',price:2.50,color:0x51372b,kind:'pack'},{id:'omena',name:'Omena',price:.80,color:0xd72e2e,kind:'fruit'},{id:'banaani',name:'Banaani',price:.65,color:0xe9d351,kind:'fruit'},{id:'donitsi',name:'Donitsi',price:1.75,color:0xa77b50,kind:'bread'},{id:'juusto',name:'Juusto',price:3.95,color:0xf1c945,kind:'pack'},{id:'pizza',name:'Pizza',price:5.50,color:0xb75d2d,kind:'pack'},{id:'limsa',name:'Limsa',price:1.95,color:0x9b3f55,kind:'bottle'},{id:'jaatelo',name:'Jäätelö',price:2.10,color:0xebaed6,kind:'pack'}];
const fmt=n=>n.toLocaleString('fi-FI',{style:'currency',currency:'EUR'});
const STORAGE='alper-v7-shop-state';const fresh=()=>({money:30,sold:0,stock:Object.fromEntries(PRODUCT.map(x=>[x.id,6])),basket:{},customerIndex:0,orders:0});let state;try{state={...fresh(),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{state=fresh()};state.stock={...fresh().stock,...state.stock};state.basket={};const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}};
const stage=document.querySelector('#stage'),panel=document.querySelector('#panel'),modal=document.querySelector('#modal'),hint=document.querySelector('#hint');const show=(html)=>{modal.innerHTML=html;panel.classList.remove('hidden')},hide=()=>{panel.classList.add('hidden');modal.replaceChildren()},tip=t=>hint.textContent=t;let audio=null;const beep=(f=880,t=.11)=>{try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+t);o.stop(audio.currentTime+t)}catch{}};
const sync=()=>{document.querySelector('#wallet').textContent='💶 '+fmt(state.money);document.querySelector('#basket').textContent='🧺 '+Object.values(state.basket).reduce((a,b)=>a+b,0);document.querySelector('#sales').textContent='⭐ '+state.sold;save()};
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0xabc6ce);scene.fog=new THREE.Fog(0xa8c8d0,20,43);const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,110);scene.add(new THREE.HemisphereLight(0xffffff,0x71909e,2.4));const sun=new THREE.DirectionalLight(0xfff0d5,3.2);sun.position.set(-5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;scene.add(sun);
const mat=(color,roughness=.75,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const M={floor:mat(0xd7dfe2),wall:mat(0xeef4ef),trim:mat(0x486878),wood:mat(0xb4825c),metal:mat(0x8c9aa0,.43,.5),glass:new THREE.MeshPhysicalMaterial({color:0xc7effa,transparent:true,opacity:.32,roughness:.08,metalness:.1}),green:mat(0x407765),yellow:mat(0xf1c25f),dark:mat(0x26414d)};
function cube(parent,w,h,d,x,y,z,material,shadow=true){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o}
function cyl(parent,rTop,rBottom,h,x,y,z,material){const o=new THREE.Mesh(new THREE.CylinderGeometry(rTop,rBottom,h,12),material);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o}
function sphere(parent,r,x,y,z,material){const o=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),material);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o}
function label(parent,title,width=1.9,height=.38,size=75,fg='#173642',bg='#ffffff'){const c=document.createElement('canvas');c.width=512;c.height=128;let g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,512,128);g.fillStyle=fg;g.textAlign='center';g.textBaseline='middle';g.font=`bold ${size}px system-ui`;g.fillText(title,256,65,490);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;let mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide}));parent.add(mesh);return mesh}
// Real 3D interior: tiled floor, walls, large windows and ceiling fittings.
cube(scene,17,.25,16,0,-.17,0,M.floor,false);for(let x=-8;x<9;x++){cube(scene,.012,.003,16,x,.001,0,mat(0xc2cdd0),false)}for(let z=-8;z<9;z++){cube(scene,17,.003,.012,0,.002,z,mat(0xc2cdd0),false)}cube(scene,17,4,.22,0,2,-8,M.wall);cube(scene,.2,4,16,-8.5,2,0,M.wall);cube(scene,.2,4,16,8.5,2,0,M.wall);cube(scene,17,.55,.2,0,3.75,8,M.trim);cube(scene,4,3,.08,-5.7,1.7,7.95,M.glass,false);cube(scene,4,3,.08,5.7,1.7,7.95,M.glass,false);cube(scene,2.3,3,.08,0,1.7,7.95,M.glass,false);cube(scene,17,.3,.3,0,.14,-7.9,M.wood);for(let x of [-5,0,5]){let l=cube(scene,3.4,.08,.45,x,3.7,-1.5,mat(0xffffff),false);const light=new THREE.PointLight(0xffffff,8,8);light.position.set(x,3.2,-1.5);scene.add(light)}
const shopTitle=label(scene,'ALPER KAUPPA',5.4,.82,65,'#ffffff','#35685e');shopTitle.position.set(0,3,-7.86);
// Pack models: all products are geometric objects, not emojis or missing external SVG files.
function pack(prod,scale=.5){let g=new THREE.Group(),m=mat(prod.color,.55);if(prod.kind==='carton'){cube(g,.54,.84,.39,0,.45,0,m);const top=new THREE.Mesh(new THREE.ConeGeometry(.35,.32,4),m);top.rotation.y=Math.PI/4;top.position.y=1;g.add(top);cube(g,.36,.27,.01,0,.56,.201,mat(0xe8eeee));}else if(prod.kind==='bottle'){cyl(g,.18,.22,.65,0,.4,0,m);cyl(g,.11,.11,.24,0,.83,0,m);cyl(g,.13,.13,.08,0,.98,0,M.dark)}else if(prod.kind==='fruit'){sphere(g,.35,0,.38,0,m);cyl(g,.034,.04,.21,0,.79,0,mat(0x567544));sphere(g,.14,.12,.81,0,mat(0x629653))}else if(prod.kind==='bread'){let o=sphere(g,.43,0,.43,0,m);o.scale.set(1.25,.73,.85)}else{cube(g,.52,.72,.35,0,.38,0,m);cube(g,.38,.23,.012,0,.51,.18,mat(0xf2ead1))}g.scale.setScalar(scale);return g}
const shelves=[],interactables=[];
function shelf(x,z,rotation=0,items=[]){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;scene.add(g);for(let h of [.28,1.13,1.97])cube(g,3,.13,.85,0,h,0,M.wood);for(let a of [-1.38,1.38])cube(g,.095,2.25,.86,a,1.12,0,M.metal);cube(g,3,.5,.15,0,2.36,-.32,M.green);items.forEach((id,i)=>{let p=PRODUCT.find(x=>x.id===id);for(let j=0;j<3;j++){let ob=pack(p,.58);ob.position.set(-1.05+i*.71+(j%2)*.08,(i%2===0?1.2:.35),-.06+(j===2?.20:0));g.add(ob)}});const l=label(g,items.map(x=>PRODUCT.find(p=>p.id===x)?.name).join(' · '),2.8,.3,38);l.position.set(0,2.4,-.235);l.rotation.y=Math.PI; shelves.push({x,z,items,g});interactables.push({type:'shelf',x,z,items})}
shelf(-4,-3.6,0,['maito','mehu','vesi']);shelf(0,-3.6,0,['leipa','kahvi','donitsi']);shelf(4,-3.6,0,['omena','banaani','juusto']);shelf(-4,1,0,['pizza','limsa','jaatelo']);
// Checkout hardware with real conveyor, display and scanner.
const till=new THREE.Group();till.position.set(4.7,0,4.25);scene.add(till);cube(till,4.3,1.05,1.24,0,.58,0,M.wood);cube(till,2.65,.08,.92,-.55,1.14,0,M.dark);for(let i=0;i<10;i++)cube(till,.025,.007,.88,-1.75+i*.27,1.184,0,M.metal,false);cube(till,.7,.68,.12,1.44,1.56,-.3,M.dark);cube(till,.58,.46,.015,1.44,1.57,-.235,mat(0x75dcbe));cube(till,.48,.055,.36,.65,1.2,-.08,mat(0x273039));const k=label(till,'KASSA',1.35,.3,72,'#ffffff','#346b72');k.position.set(.8,.76,.64);interactables.push({type:'checkout',x:4.7,z:4.25});
// Door, delivery dock, stock room sign.
cube(scene,2.1,.12,.8,-6.6,.13,5.6,M.green);let stockLabel=label(scene,'VARASTO / TUKKU',2.6,.45,50,'#ffffff','#476d7a');stockLabel.position.set(-6,2, -7.76);interactables.push({type:'warehouse',x:-6.3,z:5});
// Character rigs: 3D mesh parts and articulated animated walking legs/arms.
function person(shirt=0x467fb1,skin=0xc59270,cap=false){let root=new THREE.Group(),body=new THREE.Group();root.add(body);let top=cube(body,.59,.83,.34,0,1.22,0,mat(shirt));top.castShadow=true;cyl(body,.115,.12,.18,0,1.78,0,mat(skin));sphere(body,.29,0,2.01,0,mat(skin));let hair=sphere(body,.3,0,2.19,-.035,mat(cap?0x424650:0x463329));hair.scale.set(1,.45,1);let limbs=[];for(let x of [-.38,.38]){let arm=new THREE.Group();arm.position.set(x,1.57,0);body.add(arm);cube(arm,.2,.68,.23,0,-.35,0,mat(shirt));sphere(arm,.115,0,-.72,0,mat(skin));limbs.push(arm)}for(let x of [-.17,.17]){let leg=new THREE.Group();leg.position.set(x,.8,0);body.add(leg);cube(leg,.23,.67,.26,0,-.32,0,mat(0x354d63));cube(leg,.26,.14,.37,0,-.71,.06,mat(0x3f3534));limbs.push(leg)}for(let x of [-.1,.1])sphere(body,.034,x,2.03,.262,mat(0x25292e));return {root,body,limbs}}
const player=person(0xeabf43,0xb67f5e,true);player.root.position.set(-1.2,0,5.7);scene.add(player.root);const crowd=[person(0x549eb6,0xc99f7a),person(0xc66b84,0xe0b997),person(0x6c9974,0xa8755e)];for(const c of crowd)scene.add(c.root);const path=[new THREE.Vector3(-7,0,6),new THREE.Vector3(-5.3,0,3),new THREE.Vector3(-3,0,.5),new THREE.Vector3(1,0,1.9),new THREE.Vector3(4.7,0,2.25),new THREE.Vector3(6.3,0,6.3)];const customerNames=['Aino','Matti','Liisa','Oskari','Emma','Elias','Sofia','Veeti','Helmi','Onni'];let crowdProgress=[.7,.43,.15];const catalog=()=>PRODUCT.map(p=>`<div class="item"><span>${p.name} <span class="small">Varasto: ${state.stock[p.id]}</span></span><span>${fmt(p.price)}</span></div>`).join('');
function customerWants(){const n=state.customerIndex%PRODUCT.length;return [PRODUCT[n],PRODUCT[(n+3)%PRODUCT.length]]}let ticket=customerWants();
const basketTotal=()=>PRODUCT.reduce((a,p)=>a+p.price*(state.basket[p.id]||0),0);const affordable=(p)=>state.stock[p.id]>(state.basket[p.id]||0);
function showShelf(s){show(`<span class="badge">TUOTEHYLLY</span><h2>Valitse tuotteet</h2><p>Asiakas pyytää: <b>${ticket.map(x=>x.name).join(' + ')}</b></p><div class="items">${s.items.map(id=>{let p=PRODUCT.find(x=>x.id===id);return `<div class="item"><span>${p.name}<br><span class="small">Jäljellä ${state.stock[id]-(state.basket[id]||0)} kpl · ${fmt(p.price)}</span></span><button data-add="${id}" ${affordable(p)?'':'disabled'}>+ Koriin</button></div>`}).join('')}</div><button class="secondary" id="close">Jatka ostoksia</button>`);modal.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=PRODUCT.find(x=>x.id===b.dataset.add);if(!affordable(p))return;state.basket[p.id]=(state.basket[p.id]||0)+1;sync();beep();tip(`${p.name} lisätty koriin!`);showShelf(s)});modal.querySelector('#close').onclick=hide}
function shopCheckout(){let sum=basketTotal();let lines=PRODUCT.filter(p=>state.basket[p.id]);show(`<span class="badge">KASSA · LEIKKIMAKSU</span><h2>Alperin kassakone</h2><p>${ticket.map(x=>x.name).join(' + ')} · Ostoslista</p><div class="items">${lines.length?lines.map(p=>`<div class="item">${p.name} × ${state.basket[p.id]} <b>${fmt(p.price*state.basket[p.id])}</b></div>`).join(''):'<div class="item">Kori on tyhjä. Mene ensin hyllylle.</div>'}</div><div class="cash">${fmt(sum)}</div><p class="small">Paina maksutapaa. Maksut ovat vain leikkiä.</p><div class="flex"><button ${sum?'':'disabled'} id="card">💳 Kortti</button><button ${sum?'':'disabled'} id="money">💶 Käteinen</button></div><div class="flex" style="margin-top:9px"><button class="secondary" id="cancel">Takaisin</button><button class="secondary" id="clear">Tyhjennä kori</button></div>`);modal.querySelector('#card').onclick=()=>finishPayment('Kortti');modal.querySelector('#money').onclick=()=>{const paid=Math.ceil(sum/5)*5;show(`<h2>💶 Anna vaihtoraha</h2><p>Asiakas maksaa <b>${fmt(paid)}</b>, ostokset ${fmt(sum)}.</p><p>Paljonko rahaa palautetaan?</p><div class="flex"><button data-guess="${(paid-sum).toFixed(2)}">${fmt(paid-sum)}</button><button data-guess="${Math.max(0,paid-sum+1).toFixed(2)}">${fmt(paid-sum+1)}</button></div><p id="changeFeedback"></p><button class="secondary" id="back">Takaisin</button>`);modal.querySelectorAll('[data-guess]').forEach(b=>b.onclick=()=>{if(Math.abs(Number(b.dataset.guess)-(paid-sum))<.01)finishPayment('Käteinen');else {modal.querySelector('#changeFeedback').textContent='Kokeile uudelleen!';beep(240)}});modal.querySelector('#back').onclick=shopCheckout};modal.querySelector('#cancel').onclick=hide;modal.querySelector('#clear').onclick=()=>{state.basket={};sync();shopCheckout()}}
function finishPayment(method){let sum=basketTotal();if(!sum)return;for(let p of PRODUCT){let qty=state.basket[p.id]||0;if(qty>state.stock[p.id]){tip('Varasto ei riitä');return}}for(let p of PRODUCT)state.stock[p.id]-=state.basket[p.id]||0;state.money=Number((state.money+sum).toFixed(2));state.sold++;state.customerIndex++;ticket=customerWants();state.basket={};sync();beep(1050,.16);show(`<span class="badge">ONNISTUI!</span><h2>✅ Maksu hyväksytty!</h2><p>Kiitos! ${method} — <b>${fmt(sum)}</b></p><p class="notice">🧾 LEIKKIKUITTI · Oikeaa rahaa ei käytetty.</p><p>Seuraava asiakas: <b>${customerNames[state.customerIndex%customerNames.length]}</b>. Tarvitsee: <b>${ticket.map(x=>x.name).join(' ja ')}</b>.</p><button id="next" class="primary">Seuraava asiakas →</button>`);modal.querySelector('#next').onclick=()=>{hide();tip('Uusi asiakas odottaa kassalla!')};crowdProgress=[.73,.43,.18]}
function warehouse(){show(`<span class="badge">TUKKU · VARASTO</span><h2>Varaston täydennys</h2><p>Tilaa 3 kappaletta tuotetta hintaan <b>3,00 €</b>. Pakettiauto tuo tavarat.</p><div class="items">${PRODUCT.map(p=>`<div class="item"><span>${p.name}<br><span class="small">Varastossa ${state.stock[p.id]} kpl</span></span><button data-buy="${p.id}" ${state.money>=3?'':'disabled'}>+3 · 3 €</button></div>`).join('')}</div><button class="secondary" id="close">Sulje</button>`);modal.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{if(state.money<3)return;state.money=Number((state.money-3).toFixed(2));state.stock[b.dataset.buy]+=3;state.orders++;sync();beep(640,.18);tip('🚚 Toimitus saapui! +3 tuotetta');warehouse()});modal.querySelector('#close').onclick=hide}
const nearest=()=>{let best=null,dist=999;for(let a of interactables){let d=Math.hypot(player.root.position.x-a.x,player.root.position.z-a.z);if(d<dist){dist=d;best=a}}return dist<2.9?best:null};function interact(){let a=nearest();if(!a){tip('Mene lähemmäs hyllyä tai kassaa.');return}if(a.type==='shelf')showShelf(a);else if(a.type==='warehouse')warehouse();else shopCheckout()};document.querySelector('#act').onclick=interact;document.querySelector('#checkout').onclick=shopCheckout;document.querySelector('#help').onclick=()=>show(`<h2>Alper Kauppa 3D</h2><div class="welcome-cover"><b>OMA SUPERMARKETTI!</b><p>Liiku nuolilla tai näppäimillä WASD. Kävele hyllyn luokse ja paina Toimi. Lisää tuotteita koriin ja mene kassalle. Toimitukset saat varaston luota.</p></div><p>Asiakas haluaa: <b>${ticket.map(p=>p.name).join(' ja ')}</b>.</p><div class="flex"><button id="continue">Jatka</button><button id="reset" class="secondary">Aloita alusta</button></div>`);modal.querySelector('#continue').onclick=hide;modal.querySelector('#reset').onclick=()=>{if(confirm('Aloitetaanko uusi peli?')){state=fresh();ticket=customerWants();sync();hide()}};
show(`<span class="badge">ENSIMMÄINEN 3D-VERSIO</span><h2>Tervetuloa, Alper! 🛒</h2><p>Olet oman kauppasi kassanhoitaja. Liiku kaupassa, hae tuotteita, palvele asiakasta ja ansaitse leikkirahaa.</p><div class="welcome-cover"><b>🏪 3D-MARKETTI</b><p>Hyllyt, tuotteet, ihmiset ja kassa ovat oikeita kolmiulotteisia objekteja. Peli toimii puhelimella ja tietokoneella.</p></div><p class="small">Vaatii verkkoyhteyden Three.js-kirjaston lataamiseen. Ei oikeita kortti- tai rahamaksuja.</p><button id="go" class="primary" style="width:100%">Aloita peli ▶</button>`);modal.querySelector('#go').onclick=()=>{hide();beep(740)};
const pressed=new Set();const keyMap={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};window.addEventListener('keydown',e=>{if(keyMap[e.key]){pressed.add(keyMap[e.key]);e.preventDefault()}if(e.key==='e'&&panel.classList.contains('hidden'))interact()});window.addEventListener('keyup',e=>pressed.delete(keyMap[e.key]));document.querySelectorAll('[data-move]').forEach(b=>{const val=b.dataset.move;for(const ev of ['pointerdown'])b.addEventListener(ev,e=>{e.preventDefault();pressed.add(val);b.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>pressed.delete(val))});document.addEventListener('visibilitychange',()=>{if(document.hidden)pressed.clear()});
const clock=new THREE.Clock();let prev=0;function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.045),elapsed=clock.elapsedTime;let dx=(pressed.has('right')?1:0)-(pressed.has('left')?1:0),dz=(pressed.has('down')?1:0)-(pressed.has('up')?1:0),moving=!!(dx||dz)&&panel.classList.contains('hidden');if(moving){let length=Math.hypot(dx,dz);dx/=length;dz/=length;let x=player.root.position.x+dx*dt*3.5,z=player.root.position.z+dz*dt*3.5;let blocked=shelves.some(s=>Math.abs(x-s.x)<1.85&&Math.abs(z-s.z)<1.1)||x>2.1&&x<7.3&&z>3.25&&z<5.2;if(!blocked){player.root.position.x=THREE.MathUtils.clamp(x,-7.6,7.6);player.root.position.z=THREE.MathUtils.clamp(z,-6.8,7.3)}player.root.rotation.y=Math.atan2(dx,dz)}player.limbs.forEach((v,i)=>v.rotation.x=moving?Math.sin(elapsed*10+(i%2?Math.PI:0))*.45:THREE.MathUtils.lerp(v.rotation.x,0,.1));for(let i=0;i<crowd.length;i++){let c=crowd[i];crowdProgress[i]=(crowdProgress[i]+dt*.035)%1;let f=crowdProgress[i]*(path.length-1),j=Math.min(path.length-2,Math.floor(f)),t=f-j;let p=new THREE.Vector3().lerpVectors(path[j],path[j+1],t);c.root.position.copy(p);c.root.rotation.y=Math.atan2(path[j+1].x-path[j].x,path[j+1].z-path[j].z);c.limbs.forEach((v,k)=>v.rotation.x=Math.sin(elapsed*6+i+k%2*Math.PI)*.32)}let focus=player.root.position.clone();let desired=focus.clone().add(new THREE.Vector3(7,9.8,11));camera.position.lerp(desired,.07);camera.lookAt(focus.x,1,focus.z);if(elapsed-prev>1.5){let a=nearest();document.querySelector('#act').disabled=!a;prev=elapsed}renderer.render(scene,camera)}animate();sync();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
